### PR TITLE
feat(commitlint): enforce conventional commit

### PR DESCRIPTION
**Pull request by comoser**
enforce conventional commits throughout the monorepo

### CODE REVIEW

**Comment by comoser** [comment]
> @david Please add a `CONTRIBUTING.md` with this type of information so that everyone is aware.
> 
> You can find inspiration here https://github.com/luisFilipePT/github-covid-finder/blob/master/CONTRIBUTING.md if it helps

@luisFilipePT give it a go again 😉

**Comment by luisFilipePT** [comment]
> > @david Please add a `CONTRIBUTING.md` with this type of information so that everyone is aware.
> > You can find inspiration here https://github.com/luisFilipePT/github-covid-finder/blob/master/CONTRIBUTING.md if it helps
> 
> @luisFilipePT give it a go again 😉

@s0 already discussed this with @comoser we think that its better on the topic of repo documentation to have at the root level of the repo:

* All contributors (contributors from all projects each one might or not have it's own contributors)
* A generic README that points to the specific projects README on how to get more information on those
* General CONTRIBUTING guidelines that point again to specific guidelines in each project
* The CODE_OF_CONDUCT should be only one so everyone could point to the root, however there might have the need to have it also at the project level an in this case it should be a copy or maybe an automated flow on changes of the original
* Same for the LICENCE

At the project Level 
* A custom README pointing to the generic README when relevant, Like code of conduct and contributors
* A custom contributing with specifics for the project and linking to the main one on generic info

@comoser @s0 what is your input on this?

**Comment by comoser** [comment]
> > > @david Please add a `CONTRIBUTING.md` with this type of information so that everyone is aware.
> > > You can find inspiration here https://github.com/luisFilipePT/github-covid-finder/blob/master/CONTRIBUTING.md if it helps
> > 
> > 
> > @luisFilipePT give it a go again 😉
> 
> @s0 already discussed this with @comoser we think that its better on the topic of repo documentation to have at the root level of the repo:
> 
> * All contributors (contributors from all projects each one might or not have it's own contributors)
> * A generic README that points to the specific projects README on how to get more information on those
> * General CONTRIBUTING guidelines that point again to specific guidelines in each project
> * The CODE_OF_CONDUCT should be only one so everyone could point to the root, however there might have the need to have it also at the project level an in this case it should be a copy or maybe an automated flow on changes of the original
> * Same for the LICENCE
> 
> At the project Level
> 
> * A custom README pointing to the generic README when relevant, Like code of conduct and contributors
> * A custom contributing with specifics for the project and linking to the main one on generic info
> 
> @comoser @s0 what is your input on this?

Actually just made a PR with a unification of the thing.

SO:
- root `README` explaining project and mentioning sub projects `README`s'
- root `CONTRIBUTING` mentioning sub projects `CONTRIBUTING`s' with specific details for projects
- removed `LICENSE` from `site` -> now only on root
- removed `CODE_OF_CONDUCT` from `site` -> now only on root

**Comment by luisFilipePT** [comment]
@all-contributors please add @comoser for code,  doc, ideas, maintenance, review and projectManagement

**Comment by s0** [comment]
Yep I agree with you both on all counts re: this =)

**Pull request merged**
